version: "3"

services:
  db:
    image: mariadb
    env_file: .env.prod
    networks:
      - webapp
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file: .env.prod
    command: sh scripts/run.sh
    depends_on:
      - db
    networks:
      - webapp
networks:
  webapp: {}
