export const IS_LOADING             = "IS_LOADING";
export const REDIRECT_TEST_DESIGN   = "REDIRECT_TEST_DESIGN";
export const REDIRECT_DEFECTS       = "REDIRECT_DEFECTS";
export const REDIRECT_EXEC_CYCLE    = "REDIRECT_EXEC_CYCLE";
